# Generated by Django 5.2.4 on 2025-09-12 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de Desconto')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_from', models.DateTimeField(verbose_name='Válido de')),
                ('valid_to', models.DateTimeField(verbose_name='Válido até')),
            ],
        ),
    ]
