# Generated by Django 5.2.4 on 2025-09-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(help_text='Ex: Capacidade, Polegada', max_length=50, verbose_name='Tipo da Opção')),
                ('value', models.CharField(help_text='Ex: 128GB, 15 polegadas', max_length=50, verbose_name='Valor da Opção')),
                ('price_increase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Acréscimo no Preço')),
                ('order', models.PositiveIntegerField(default=0, help_text='Use para ordenar as opções (0 primeiro, 1 depois, etc.)', verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
