# Generated by Django 5.2.4 on 2025-09-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_capacity_options',
            field=models.BooleanField(default=True, help_text='Marque esta opção se este produto tiver opções de capacidade (ex: 128GB, 256GB).', verbose_name='Habilitar opções de capacidade?'),
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
