# Generated by Django 5.2.4 on 2025-12-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customuser_bairro_customuser_cep_customuser_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Rua'),
        ),
    ]
